/**
 * Bibliothèque d icônes hi2 pour le canvas.
 */
export const CANVAS_ICON_ENTRIES = Object.freeze([
  { name: 'HiPhone', label: 'Téléphone' },
  { name: 'HiDevicePhoneMobile', label: 'Mobile' },
  { name: 'HiEnvelope', label: 'Email' },
  { name: 'HiLink', label: 'Lien' },
  { name: 'HiGlobeAlt', label: 'Site web' },
  { name: 'HiMapPin', label: 'Lieu' },
  { name: 'HiHome', label: 'Maison' },
  { name: 'HiCalendar', label: 'Calendrier' },
  { name: 'HiClock', label: 'Horloge' },
  { name: 'HiBriefcase', label: 'Mallette' },
  { name: 'HiBuildingOffice', label: 'Bureau' },
  { name: 'HiBuildingOffice2', label: 'Entreprise' },
  { name: 'HiAcademicCap', label: 'Diplôme' },
  { name: 'HiBookOpen', label: 'Livre' },
  { name: 'HiUser', label: 'Profil' },
  { name: 'HiUsers', label: 'Équipe' },
  { name: 'HiUserGroup', label: 'Groupe' },
  { name: 'HiStar', label: 'Étoile' },
  { name: 'HiHeart', label: 'Cœur' },
  { name: 'HiHandThumbUp', label: 'Pouce' },
  { name: 'HiLightBulb', label: 'Idée' },
  { name: 'HiBolt', label: 'Énergie' },
  { name: 'HiFire', label: 'Feu' },
  { name: 'HiSparkles', label: 'Sparkles' },
  { name: 'HiChartBar', label: 'Barres' },
  { name: 'HiChartPie', label: 'Camembert' },
  { name: 'HiArrowTrendingUp', label: 'Hausse' },
  { name: 'HiCurrencyEuro', label: 'Euro' },
  { name: 'HiBanknotes', label: 'Finance' },
  { name: 'HiShoppingCart', label: 'Commerce' },
  { name: 'HiTruck', label: 'Logistique' },
  { name: 'HiCodeBracket', label: 'Code' },
  { name: 'HiCommandLine', label: 'Terminal' },
  { name: 'HiCpuChip', label: 'Tech' },
  { name: 'HiCloud', label: 'Cloud' },
  { name: 'HiServer', label: 'Serveur' },
  { name: 'HiLanguage', label: 'Langue' },
  { name: 'HiChatBubbleLeft', label: 'Message' },
  { name: 'HiMegaphone', label: 'Annonce' },
  { name: 'HiMicrophone', label: 'Micro' },
  { name: 'HiCamera', label: 'Photo' },
  { name: 'HiVideoCamera', label: 'Vidéo' },
  { name: 'HiPlay', label: 'Lecture' },
  { name: 'HiMusicalNote', label: 'Musique' },
  { name: 'HiPaintBrush', label: 'Design' },
  { name: 'HiWrench', label: 'Outil' },
  { name: 'HiCog6Tooth', label: 'Réglages' },
  { name: 'HiShieldCheck', label: 'Sécurité' },
  { name: 'HiLockClosed', label: 'Verrou' },
  { name: 'HiKey', label: 'Clé' },
  { name: 'HiCheckBadge', label: 'Badge' },
  { name: 'HiCheckCircle', label: 'OK' },
  { name: 'HiXCircle', label: 'Non' },
  { name: 'HiExclamationTriangle', label: 'Alerte' },
  { name: 'HiInformationCircle', label: 'Info' },
  { name: 'HiQuestionMarkCircle', label: 'Aide' },
  { name: 'HiRocketLaunch', label: 'Lancement' },
  { name: 'HiPaperAirplane', label: 'Envoi' },
  { name: 'HiDocumentText', label: 'Document' },
  { name: 'HiFolder', label: 'Dossier' },
  { name: 'HiArchiveBox', label: 'Archive' },
  { name: 'HiGift', label: 'Cadeau' },
  { name: 'HiTrophy', label: 'Trophée' },
  { name: 'HiFlag', label: 'Drapeau' },
  { name: 'HiTag', label: 'Tag' },
  { name: 'HiHashtag', label: 'Hashtag' },
  { name: 'HiAtSymbol', label: '@' },
  { name: 'HiWifi', label: 'Wi-Fi' },
  { name: 'HiSignal', label: 'Signal' },
  { name: 'HiBeaker', label: 'Science' },
  { name: 'HiHeartPulse', label: 'Santé' },
]);

export function createIconBlockPreset(iconName, color = '#1e293b') {
  return {
    type: 'icon',
    icon_name: iconName,
    w: 10,
    h: 10,
    style: { color },
  };
}
